### ISSUE TITLE
Homebrew-Cadfael failed installation at CCLYON

### ISSUE THREAD

**Issue by Tedjditi** [SuperNEMO-DBD/homebrew-cadfael#37]
Dears developers,

I tried to install Homebrew-cadfael on SL6.9 on CCLYON

I executed:

$ git clone https://github.com/SuperNEMO-DBD/brew.git ~/CadfaelBrew
$ cd CadfaelBrew/
$ ./bin/brew cadfael-bootstrap

it end with the error:
[ErrorBootstrap.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1479158/ErrorBootstrap.txt)

Result of the /brew config :
[Config.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1479163/Config.txt)
 
Output of /brew doctor
[Doctor.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1479170/Doctor.txt)

When i try to install git ./brew install git i get the error:
[ErrorGit.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1479176/ErrorGit.txt)

so i do brew install glibc and i get the error:
[Errorglibc.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1479183/Errorglibc.txt)

And when i try to install gcc : 
[Errorgcc.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1479188/Errorgcc.txt)

I already had the problem of installing HEP_OSlibs_SL6 and i had to ask the informatics department to install it as it is furnished as a metapackage. 

Brew is up to date

Thanks for your help

**Comment by Tedjditi** [comment]
HEP_OSlibs_SL6 is not installed on CCLYON,

I had this problem when i tried to install Homebrew-cadfael on a local computer of my lab, i tried to install it by myself but it was a metapackage so i needed to ask the informatics department of my lab to installed it.

**Comment by lemiere** [comment]
Hi,

That's not easy to install all our stuff at CCLYON due to many things...
(I will report on it)
nemoprod account provide a shared installation up to bayeux3.1.
To use it  : 
export PATH=/sps/nemo/sw/simulation/linux_brew/brew/bin:$PATH
. /sps/nemo/sw/simulation/linux_brew/brew/opt/root6/libexec/thisroot.sh
unset LD_LIBRARY_PATH

At this level, you will able to install your own Falaise at CCLYON.
Let me know if you need help.

**Comment by icefinger** [comment]
Hi, I have a couple of questions about this issue.
Isn't the goal of cadafael-brew to make easy to install falaise bayeux and other easy anywhere?
I think it should work out of the box at least at Lyon, it's an important issue from my point of view.
He needs it not only for production but also for development, so he needs his own installation of falaise. Even for development it's important to have it at Lyon, because even for the test we need statistics.
Greetings

**Comment by lemiere** [comment]
Not so easy!
There is many link to base lib.... and many version are available at CCLYON. (have a look after LD_LIBRARY_PATH and PATH). You will have conflict not so easy to solve even if you use brew.
So I did it for SuperNEMO collaboration.
Anyway : I propose a common base software up to bayeux3.1 and users have to install their own Falaise at CCLYON for dev. (or unblessed prod)

**Comment by drbenmorgan** [comment]
Closing Issues not updated in more than 2 months. Reopen if required, or start a new issue.
