### ISSUE TITLE
Root 6.08.06 does not build on Falaise install 3.1.1, High Sierra, Xcode 9.1

### ISSUE THREAD

**Issue by lecdawson** [SuperNEMO-DBD/homebrew-cadfael#38]
### Bug reports:
Upgraded to Mac OS High Sierra. Tried to install new falaise version 3.1.1, and root 6.08.06 will not build. 

brew gist-logs root6 link:
https://gist.github.com/anonymous/0284e3af41402c1d176398b3ee611f1e

**Comment by drbenmorgan** [comment]
This is a known issue with Xcode 9 - and requires further work on getting everything to run. It should be possible to get Xcode 8 from the Apple Developer site: https://developer.apple.com/xcode/ and put in `/Applications/Xcode8.app`. Then run `xcode-select -s /Applications/Xcode8.app`. After than things should use the tools from there.

Otherwise, you can try installing the `HEAD` version of root:

```
$ brew install root6 --HEAD
```

but no guarantees this'll work. There are also likely issues with Qt5 as well.

**Comment by lecdawson** [comment]
Ok, thank you Ben. I will try using the earlier version of Xcode.

**Comment by lecdawson** [comment]
Update: 
When I installed Xcode8 and selected this version, brew will not run:
Error: Your Xcode (8.3.3) is too outdated.
Please update to Xcode 9.0 (or delete it).
Xcode can be updated from
  https://developer.apple.com/download/more/

Having switched back to Xcode9.1 I am now trying to install root6 HEAD. I have renamed Xcode9.1 to Xcode-beta.app and switched using: 
sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer/

Unfortunately root6 HEAD will not also fails during the build

**Comment by HanFangXie** [comment]
I have exactly the same problem now. How is it sloved at last?

**Comment by drbenmorgan** [comment]
Addressed by #40 

Note that this will also require a new patch release of Falaise (though `brew install falaise --HEAD` works using the changes in #40)
